# Generated by Django 5.2.5 on 2025-09-04 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='car',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='django_app.car'),
        ),
    ]
