spring:
  profiles:
    active: oracle
    # active: postgres
    # active: mssql
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.boot.autoconfigure.orm.jpa: INFO
