spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=java_spring_jpa_db;trustServerCertificate=true
    username: java_spring_jpa_user
    password: Password123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
